main: io.github.chouyoux.realmsofchaos.RealmsOfChaos
name: RealmsOfChaos
version: 0.0.1-SNAPSHOT
api-version: 1.16
author: Alexis (Chouyoux) Flazinska
description: A core plugin to run the RealmOfChaos game of a Spigot Server
depend: [WorldEdit, WorldGuard, SpigotLib, EffectLib, WorldGuardEvents, NBTAPI, GlowAPI, LibsDisguises, ProtocolLib, Citizens, Sentinel]
commands:
    roclear:
       description: Clears all entities spawned by this plugin
       usage: /roclear
       permission: roc.roclear
       permission-message: You need to be OP.
    get:
       description: Gets a player's field's value
       usage: /get <OnlinePlayer> <Field>
       permission: roc.get
       permission-message: You need to be OP.
    set:
       description: Sets a player's field's value
       usage: /set <OnlinePlayer> <Field> <Value>
       permission: roc.set
       permission-message: You need to be OP.
    tuto:
       description: Teleporter a player to the tutorial
       usage: /tuto
    join:
       description: Generates a request to join a player's challenge
       usage: /join <OnlinePlayer>
    accept:
       description: Accept an invitation request
       usage: /accept <OnlinePlayer>
    challengestats:
       description: Displays info about a player's running Challenge
       usage: /challengestats <OnlinePlayer>
       permission: roc.challengestats
       permission-message: You need to be OP.
    it:
       description: Gives RoC materials
       usage: /it [<OnlinePlayer>] <ID> <Amount>
       permission: roc.it
       permission-message: You need to be OP.
    chaos:
       description: Summons RoC Chaos Entities
       usage: /chaos <ChaosMob> [<Quantity>]
       permission: roc.chaos
       permission-message: You need to be OP.
    cd:
       description: Resets all cooldowns
       usage: /cd [<OnlinePlayer>]
       permission: roc.cd
       permission-message: You need to be OP.
